# Generated by Django 3.1.7 on 2021-04-09 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
