# Generated by Django 3.1.7 on 2021-03-30 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jpapp', '0002_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='memo',
            new_name='task_memo',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='task_title',
        ),
    ]
