# Generated by Django 3.1.7 on 2021-03-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0003_auto_20210330_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phase',
            field=models.CharField(choices=[('light', 'document_screening'), ('light', 'information_session'), ('alert', 'first_interview'), ('alert', 'second_interview'), ('alert', 'third_interview'), ('alert', 'fourth_interview'), ('danger', 'pass'), ('dark', 'failure')], default='light', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='establishd',
            field=models.DateField(null=True),
        ),
    ]
