# Generated by Django 3.1.7 on 2021-03-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0004_auto_20210330_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phase',
            field=models.CharField(choices=[('書類選考', 'document_screening'), ('カジュアル面談', 'information_session'), ('一次面接', 'first_interview'), ('二次面接', 'second_interview'), ('三次面接', 'third_interview'), ('四次面接', 'fourth_interview'), ('内定', 'pass'), ('お見送り', 'failure')], default='light', max_length=50),
        ),
    ]
