# Generated by Django 3.1.7 on 2021-04-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0005_auto_20210414_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tags',
            new_name='tag',
        ),
    ]
