# Generated by Django 3.1.7 on 2021-03-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0006_auto_20210331_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phase',
            field=models.IntegerField(choices=[(0, '書類選考'), (1, 'カジュアル面談'), (2, '一次面接'), (3, '二次面接'), (4, '三次面接'), (5, '四次面接'), (6, '内定'), (7, 'お見送り')], default='0'),
        ),
    ]
