# Generated by Django 3.1.7 on 2021-05-02 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0007_auto_20210429_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
    ]
