# Generated by Django 3.1.7 on 2021-04-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0010_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='application_date',
            field=models.DateField(null=True),
        ),
    ]
