# Generated by Django 3.1.7 on 2021-04-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0013_auto_20210408_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='business_form',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
