# Generated by Django 3.1.7 on 2021-04-08 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jpapp', '0014_auto_20210408_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='business_form',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='route',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
